set nocompatible              " be iMproved, required
filetype off                  " required

"Leader Key 'space'
let mapleader=" "


" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"Plugins
Plugin 'morhetz/gruvbox'
Plugin 'scrooloose/nerdtree'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'SirVer/ultisnips'
Plugin 'lervag/vimtex'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
call vundle#end()            " required
filetype plugin indent on    " required

"Ultisnips trigger and settings
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsListSnippets = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
let g:UltiSnipsEditSplit = "vertical"
map <leader>e :UltiSnipsEdit<cr>
autocmd! User UltiSnipsEnterFirstSnippet

"Lightline config 
let g:lightline = {
    \ 'colorscheme': 'PaperColor',
    \ 'active': {
    \    'left': [ [ 'mode', 'paste'],
    \              [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'FugitiveHead'
    \ },
    \ }

"Vim theme
let g:gruvbox_contrast_dark="hard" 
colorscheme gruvbox

"Nerdtree options
let NERDTreeQuitOnOpen=1

"Vimtext config
let g:tex_flavor='latex'
let g:vimtex_view_method='mupdf'
let g:vimtex_quickfix_mode=0
inoremap <F2> <esc>:set spell!<cr>
nnoremap <F2> :set spell!<cr>
set spelllang=es,en_us



"Non-plugin stuff
syntax enable
set number
set bg=dark
set clipboard=unamed

"Space and tab configuration
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

"Encode
set encoding=utf-8

" No show mode for insert..and so on
set noshowmode

"Satus line config
set laststatus=2

"Mouse enable on vim 
set mouse=a
set numberwidth=1
set showcmd
set ruler
set hlsearch "resaltar patrones de busqueda.

"Keymaps
nmap <Leader>nt :NERDTreeFind<CR>
nmap <Leader>w :w<CR>
nmap <Leader>q :q<CR>
nmap <Leader>hl :set hlsearch! hlsearch?<CR>
